openapi: 3.0.0
info:
  title: expand
  version: "0.3"
paths: {}
components:
  schemas:
    expand:
      type: object
      required:
        - init
      properties:
        init:
          type: string
        optional:
          type: integer
        withDefault:
          type: string
          enum:
            - foo
            - bar
            - baz
          default: foo
