on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - '**'
name: Test
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go-version: ['1.20']
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v3
        run: go run github.com/cue-unity/unity/cmd/unity test --verbose
